- name: Actualizar repos
  apt:
    update_cache: yes

- name: Instalar dependencias
  apt:
    name:
      - software-properties-common
      - uidmap
    state: present

- name: Añadir repositorio oficial de Podman
  apt_repository:
    repo: ppa:projectatomic/ppa
    state: present

- name: Instalar Podman
  apt:
    name: podman
    state: present
    update_cache: yes