---
# - name: Permitir puertos <1024 en rootless (habilitar 80)
#   become: true
#   ansible.posix.sysctl:
#     name: net.ipv4.ip_unprivileged_port_start
#     value: "80"
#     state: present
#     reload: true

# - name: Eliminar contenedor anterior si existe
#   containers.podman.podman_container:
#     name: "{{ vm_container_name }}"
#     state: absent
#   ignore_errors: true
- block:

    - name: Login en ACR (rootless)
      containers.podman.podman_login:
        registry: "{{ acr_login_server }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
      no_log: true

    # Evita el “Cannot create container when image is not specified!”
    # directamente ausente (idempotente y no requiere image)
    - name: Eliminar contenedor anterior si existe (rootless)
      containers.podman.podman_container:
        name: "{{ vm_container_name }}"
        state: absent
      ignore_errors: true

    - name: Asegurar imagen presente desde ACR (rootless)
      containers.podman.podman_image:
        name: "{{ acr_login_server }}/{{ acr_repo }}"
        tag: "{{ acr_tag }}"
        pull: true
        state: present

    - name: Arrancar contenedor actualizado (rootless 8080->80)
      containers.podman.podman_container:
        name: "{{ vm_container_name }}"
        image: "{{ acr_login_server }}/{{ acr_repo }}:{{ acr_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ vm_host_port }}:{{ vm_container_port }}"

  become: false