- name: Login en ACR
  command: >
    podman login {{ acr_login_server }}
    --username {{ acr_username }}
    --password {{ acr_password }}

- name: Descargar imagen desde Docker Hub
  command: podman pull docker.io/library/nginx:latest

- name: Etiquetar imagen para Podman
  command: >
    podman tag nginx:latest
    {{ acr_login_server }}/podman/hola-mundo:casopractico2

- name: Etiquetar imagen para Kubernetes
  command: >
    podman tag nginx:latest
    {{ acr_login_server }}/kubernetes/hola-mundo:casopractico2

- name: Subir imagen Podman al ACR
  command: >
    podman push {{ acr_login_server }}/podman/hola-mundo:casopractico2

- name: Subir imagen Kubernetes al ACR
  command: >
    podman push {{ acr_login_server }}/kubernetes/hola-mundo:casopractico2

- name: Eliminar contenedor previo si existe
  command: podman rm -f nginx-demo
  ignore_errors: yes

- name: Ejecutar contenedor Nginx desde ACR
  command: >
    podman run -d --name nginx-demo -p 80:80
    {{ acr_login_server }}/podman/hola-mundo:casopractico2