# ACR
acr_login_server: "acrdevopsalfredo.azurecr.io"
acr_name: "acrdevopsalfredo"
acr_image: "webapp"
acr_tag: "casopractico2"
acr_repo: "webapp"

build_context: "{{ role_path }}/files"
dockerfile_path: "{{ role_path }}/files/Dockerfile"



# VM / Podman
vm_container_name: "webapp"
vm_container_port: 80
vm_host_port: 8080

# AKS
aks_name: "aks-devops"
aks_rg: "rg-devops-azure"
aks_namespace: "unir"