- name: Obtener credenciales del AKS
  ansible.builtin.command: >
    az aks get-credentials
    --resource-group {{ aks_rg }}
    --name {{ aks_name }}
    --overwrite-existing
  changed_when: false

- name: Aplicar manifiesto con módulo Kubernetes (sin kubectl)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deploy.yaml.j2') }}"
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"

- name: Esperar a que el Deployment frontend esté ready
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ aks_namespace }}"
    name: frontend
  register: deploy_info
  until: deploy_info.resources[0].status.readyReplicas == deploy_info.resources[0].spec.replicas
  retries: 10
  delay: 6

- name: Obtener servicios del namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ aks_namespace }}"
    name: frontend-service
  register: svc_info

- name: Mostrar IP pública
  debug:
    msg: "APP disponible en http://{{ svc_info.resources[0].status.loadBalancer.ingress[0].ip }}"