---
- name: Configurar VM con Podman y acceso a ACR
  hosts: all
  become: yes

  vars:
    acr_login_server: "{{ lookup('env', 'ACR_LOGIN_SERVER') }}"
    acr_username: "{{ lookup('env', 'ACR_USERNAME') }}"
    acr_password: "{{ lookup('env', 'ACR_PASSWORD') }}"

  tasks:

    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar Podman
      apt:
        name: podman
        state: present

    - name: Crear directorio de autenticación
      file:
        path: /home/devops/.config/containers
        state: directory
        owner: devops
        group: devops
        mode: '0755'

    - name: Login en ACR
      become_user: devops
      shell: |
        podman login {{ acr_login_server }} \
          -u {{ acr_username }} \
          -p {{ acr_password }}