- name: Configurar VM con Podman y subir imágenes al ACR
  hosts: vm_podman
  become: true

  vars:
    acr_login_server: "acr-devops-alfredo.azurecr.io"
    acr_username: "<usuario_acr>"
    acr_password: "<password_acr>"

  roles:
    - podman_install
    - acr_images