# Imagen a desplegar (subida previamente al ACR)
acr_login_server: ""
acr_repo: "webapp"
acr_tag: "1.0"

# Credenciales (rellenadas desde secrets.yml a nivel de playbook)
acr_username: ""
acr_password: ""

# Contenedor en la VM
vm_container_name: "webapp"
vm_container_port: 8080      # puerto dentro del contenedor
vm_host_port: 80            # puerto expuesto en la VM

# Herramientas
install_podman: true
install_python: true       
use_podman_cli: true        # usa CLI de podman (si false, podrías cambiar a módulos)

