base_image: "docker.io/library/nginx:alpine"
acr_repo: "webapp"
acr_tag: "casopractico2"

build_context: "{{ role_path }}/files"
dockerfile_path: "{{ role_path }}/files/Dockerfile"

use_podman: true
push_image: true